version: '3.4'


services:
  es.service:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es-container
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- TAKE_FILE_OWNERSHIP=true
    volumes:
      - "./mydata/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./mydata/elasticsearch/data:/usr/share/elasticsearch/data"
      - "./mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
    networks:
      - es-net

  kibana.service:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana-container
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - es.service
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    volumes:
      - "./mydata/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"
    networks:
      - es-net

networks:
  es-net:
    driver: bridge
