version: '2'


services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - db.env

  app:
    image: yiyungent/nextcloud
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    env_file:
      - db.env
    privileged: true
    user: root
